### ISSUE TITLE
Uncaught ErrorException: Array to string conversion

### ISSUE THREAD

**Issue by MiFrance** [giuscris/formwork#14]
Hi,
Get my french language pack:
[fr.yml.zip](https://github.com/giuscris/formwork/files/2975036/fr.yml.zip)

Now if you select French in profile, you get a error for edit page:
`PHP Fatal error:  Uncaught ErrorException: Array to string conversion in /formwork/admin/views/fields/checkbox.php:4`

**Comment by giuscris** [comment]
Hi @MiFrance,
first of all thank you for the French language pack. Could you make a PR when it's done?

Thank you also for discovering the bug! It happens since you don't have the labels in French for the template fields in `/templates/schemes/`.
In the next commit I'll fix it making it switch to a fallback language.

**Comment by giuscris** [comment]
Fixed issue with last commit, thank you again!

**Comment by MiFrance** [comment]
Ho ok, I did not look in templates!
Why not use a global variable here too?

**Comment by giuscris** [comment]
Actually you can already do that using `'{{language.string.name}}'` syntax. Template schemes should be definitely updated, at least with strings for some common names. I'll open an enhancement issue referencing your suggestion.
