### ISSUE TITLE
Bug for multi language on page save

### ISSUE THREAD

**Issue by Wemago** [giuscris/formwork#528]
There's a bug on saving when multi languages are selected.

To reproduce:
1. Select at least two languages on options > system > languages
2. Edit hello world blog post on pages > blog > hello world
3. Save for both languages
4. Result: the page is moved out of the blog to the root path and we can't set a parent to that edited page.

**Comment by giuscris** [comment]
Hello @Wemago thank you for reporting the bug.
I've noticed first level pages are not having this issue, but you can't edit the translations after you have created them.
I need to investigate more to understand the problem.

**Comment by giuscris** [comment]
@Wemago the bug you found wasn't really related to languages. The problem was in the parent page field, it didn't select the correct parent page for a typo in the view (see https://github.com/getformwork/formwork/commit/1187cfde503073a2e730921661f70a8491020ea4).

The problem with the editor has been solved with https://github.com/getformwork/formwork/commit/221aad55084ceae4557671034e0dc77a20913cab .

Could you try pulling the latest two commits and check if the bug is gone?

**Comment by Wemago** [comment]
It's gone. Thanks 💯
